# Generated by Django 5.2 on 2025-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_generator", "0002_generatedcontent_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcontent",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
